version: '3.9'

services:
  db:
    container_name: db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=movie_db
    image: postgres:latest
    networks:
      - movie_network

  app:
    container_name: movie
    image: poviraevsergei/movie:v2
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
    depends_on:
      - db
    networks:
      - movie_network

networks:
  movie_network:
    driver: bridge